oml_feed_reader_homepage:
    pattern:  /
    defaults: { _controller: omlFeedReaderBundle:Public:index }

index:
    pattern: /
    defaults: { _controller: omlFeedReaderBundle:Public:index }

about:
    pattern: /about
    defaults: { _controller: omlFeedReaderBundle:Public:about }
