parameters:
#    oml_feed_reader.example.class: oml\FeedReaderBundle\Example

services:
#    oml_feed_reader.example:
#        class: %oml_feed_reader.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
